[package]
name = "bevy_sky_gradient"
version = "0.1.0"
edition = "2024"

[features]
default = ["cycle"]
# our built in day-night cycle implementation, uses cycle::Gradient
cycle = ["egui-colorgradient", "bevy-inspector-egui"]

[dependencies]
bevy = "0.16"
rust-embed = "8" # to embed assets like .wgsl

egui-colorgradient = {version="0.2.3", optional = true}
bevy-inspector-egui = {version = "0.33", optional = true}

[dev-dependencies]
bevy_flycam = "0.16.1"
